export const constants = {
  HAS_SAME_CHARACTERS: 'HAS_SAME_CHARACTERS',
  HAS_DIFFERENT_CHARACTERS: 'HAS_DIFFERENT_CHARACTERS',
  ADJACENT_CHARACTERS: 'ADJACENT_CHARACTERS',
  NO_RESULT: 'NO_RESULT',
  USER_BALANCE_ZERO: 'USER_BALANCE_ZERO',
  MACHINE_BALANCE_LOW: 'MACHINE_BALANCE_LOW'
}

export const costPerPlay = 20
